services:
  synopsar-ui:
    build: ./synopsar-ui
    ports:
      - "3000:3000"

  transcriptor:
    build: ./transcriptor
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/{DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  synopsar-api:
    build: ./synopsar-api
    ports:
      - "8081:8081"
    depends_on:
      - llm
      - transcriptor
      - db
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  llm:
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    build: ./llm
    ports:
      - "5001:5001"

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "5432:5432"
    command: [ "postgres", "-cshared_preload_libraries=pg_stat_statements" ]

volumes:
  pgdata: