version: '3.8'

services:
  transcriptor:
    build: ./transcriptor
    ports:
      - "5000:5000"

  synopsar-ui:
    build: ./synopsar-ui
    ports:
      - "3000:3000"

  synopsar-api:
    build: ./synopsar-api
    ports:
      - "8081:8081"
    depends_on:
      - transcriptor
    links:
      - transcriptor:transcriptor

  llm:
    build: ./llm
    ports:
      - "5001:5001"
